document.write('a. A heading stating “Rules for naming JS variables”'+"<br/>")
document.write('b. Variable names can only contain ______, ______,'+"<br/>")
document.write('c.______ and ______.'+"<br/>")
document.write('d. For example $my_1stVariable.'+"<br/>")
document.write('e. Variables must begin with a ______, ______ or'+"<br/>")
document.write('f. _____. For example $name, _name or name'+"<br/>")
document.write('g. Variable names are case _________'+"<br/>")
document.write('h. Variable names should not be JS _________'+"<br/>")